# Generated by Django 5.0 on 2024-12-21 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attraction',
            old_name='attraction_type',
            new_name='attraction_type_id',
        ),
        migrations.RenameField(
            model_name='attraction',
            old_name='region',
            new_name='region_id',
        ),
    ]
